### 일기 상세
GET http://localhost:8080/diary/1
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrZXJpYSIsImlhdCI6MTcwMTAwMjY4OSwiZXhwIjoxNzAxMDA2Mjg5fQ.03_S-hJnES9mnC5E0fptpkB8QpDOgoRk7InHBg2SHHXsGxv3i4wUVOF19i4D9399FSpcPR8JkYPFx0s9Ic5XUQ

### 일기 목록
GET http://localhost:8080/user/3/diaries?page=0&size=10&sort=createdAt
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmYWtlciIsImlhdCI6MTcwMTE0ODc1NywiZXhwIjoxNzAxMTUyMzU3fQ.S6y2ore_oENPBP_nlJdTj7h6X6oY0mcGIL9ExJVevwdb2gYQ4kkPcVCsknBr5nGqHctnZ5eMsJsgLwJbWAtb3w

### 일기 삭제
DELETE http://localhost:8080/diary/5
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrZXJpYSIsImlhdCI6MTcwMTA2MzQwOCwiZXhwIjoxNzAxMDY3MDA4fQ.AqEaoz1szoCwOc1CmiFidXRi0eD9vWIRsC5dwmNV1_w1wYcsjpfiYSB7qnhLaGITjE3FZ82u9smvoEKrpdP3wg

### 일기 좋아요
PATCH http://localhost:8080/diary/2/like
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrZXJpYSIsImlhdCI6MTcwMTIzOTA4MCwiZXhwIjoxNzAxMjQyNjgwfQ.pgB7UXHqYv4iIEUe-HK2mQAXFWe3PSyO-aMYW8gihdShj5sS4OVucYd26eSmW7zw9W9Ywu8JWkxU4Hq2TIsc6Q

### 일기 좋아요 취소
DELETE http://localhost:8080/diary/2/cancel/like
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrZXJpYSIsImlhdCI6MTcwMTIzOTA4MCwiZXhwIjoxNzAxMjQyNjgwfQ.pgB7UXHqYv4iIEUe-HK2mQAXFWe3PSyO-aMYW8gihdShj5sS4OVucYd26eSmW7zw9W9Ywu8JWkxU4Hq2TIsc6Q

### Document 추가
POST http://localhost:8080/diary-documents
X-AUTH-TOKEN:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrZXJpYSIsImlhdCI6MTcwMTMzNDcwMSwiZXhwIjoxNzAxMzM4MzAxfQ.sfMAs17Dg-l7D5-PsHOhlqBrsYAdDN4JeP3Q8JcPrXsWUi1cZwV_1ZSwV1-BZYQTY-hxZ155ztWXc9kwEhUNbA

### 일기 검색
GET http://localhost:8080/diary/search?searchCond=diary
X-AUTH-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrZXJpYSIsImlhdCI6MTcwMTMzNDcwMSwiZXhwIjoxNzAxMzM4MzAxfQ.sfMAs17Dg-l7D5-PsHOhlqBrsYAdDN4JeP3Q8JcPrXsWUi1cZwV_1ZSwV1-BZYQTY-hxZ155ztWXc9kwEhUNbA

